[versions]
agp = "8.10.1"
kotlin = "2.1.10"
coreKtx = "1.16.0"
junit = "4.13.2"
appcompat = "1.7.0"
material = "1.12.0"
navigation = "1.0.0"
kotlin-test = "2.1.20"
mockito-kotlin = "5.4.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
navigation = { module = "com.vsulimov:navigation", version.ref = "navigation" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin-test" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
